#!/usr/bin/env bash
# Install Postgres 16, create role + database, write env file.
# Idempotent.
set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

DB_NAME="${DB_NAME:-vibe_coder_hub}"
DB_USER="${DB_USER:-vibe}"
ENV_FILE="/etc/vibe-coder-hub.env"

export DEBIAN_FRONTEND=noninteractive

echo "==> apt update + Postgres 16"
apt-get update
apt-get install -y postgresql postgresql-contrib ufw openssl ca-certificates curl
systemctl enable --now postgresql

DB_PASS="$(openssl rand -hex 24)"

echo "==> Creating role '$DB_USER'"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASS';
  ELSE
    ALTER ROLE $DB_USER WITH LOGIN PASSWORD '$DB_PASS';
  END IF;
END
\$\$;
SQL

echo "==> Creating database '$DB_NAME'"
DB_EXISTS="$(sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")"
if [[ "$DB_EXISTS" != "1" ]]; then
  sudo -u postgres createdb -O "$DB_USER" "$DB_NAME"
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 -d "$DB_NAME" <<SQL
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
GRANT ALL ON SCHEMA public TO $DB_USER;
ALTER SCHEMA public OWNER TO $DB_USER;
SQL

PUBLIC_IP="$(curl -s -4 ifconfig.me || true)"
DB_URL_LOCAL="postgres://$DB_USER:$DB_PASS@127.0.0.1:5432/$DB_NAME"
DB_URL_PUBLIC="postgres://$DB_USER:$DB_PASS@${PUBLIC_IP:-YOUR-VPS-IP}:5432/$DB_NAME?sslmode=require"

mkdir -p /etc
{
  echo "# Generated by bootstrap-postgres.sh on $(date -u)"
  echo "DATABASE_URL=$DB_URL_LOCAL"
  echo "DATABASE_URL_PUBLIC=$DB_URL_PUBLIC"
  echo "DB_NAME=$DB_NAME"
  echo "DB_USER=$DB_USER"
  echo "DB_PASS=$DB_PASS"
} > "$ENV_FILE"
chmod 0640 "$ENV_FILE"

cat <<EOF

================================================================
Postgres ready.

  Local:   $DB_URL_LOCAL
  Public:  $DB_URL_PUBLIC

Local URL works only for processes on this VPS.
For Vercel, run  expose-postgres.sh  next to enable remote TLS auth,
then copy DATABASE_URL_PUBLIC into Vercel.

Credentials are stored in $ENV_FILE (mode 0640).
================================================================
EOF
